
# folder path of dataset, which includes 2 subfolders: cloudy_image/ and ground_truth/
datasets_dir: ../gz/data/
train_list: train1.txt
test_list: test1.txt
out_dir: results

cuda: True
gpu_ids: [0]

train_size: 0.8
validation_size: 0.2 # 验证集大小是占训练集的半分比
batchsize: 6
validation_batchsize: 6
epoch: 40
n_data: 433
width: 256
height: 256
threads: 4

lr: 0.0004
beta1: 0.5
lamb: 100
minimax: 1

gen_init: 
dis_init: 
in_ch: 13
out_ch: 13

manualSeed: 0
snapshot_interval: 1